//fetch products details
export const FETCH_SORT_AREA_REQUEST = 'FETCH_SORT_AREA_REQUEST';
export const FETCH_SORT_AREA_SUCCESS = 'FETCH_SORT_AREA_SUCCESS';
export const FETCH_SORT_AREA_FAILURE = 'FETCH_SORT_AREA_FAILURE';


