//fetch products details
export const FETCH_SORT_CATEGORY_REQUEST = 'FETCH_SORT_CATEGORY_REQUEST';
export const FETCH_SORT_CATEGORY_SUCCESS = 'FETCH_SORT_CATEGORY_SUCCESS';
export const FETCH_SORT_CATEGORY_FAILURE = 'FETCH_SORT_CATEGORY_FAILURE';


