//fetch products
export const FETCH_PRODUCT_FETCH_REQUEST = 'FETCH_PRODUCT_FETCH_REQUEST';
export const FETCH_PRODUCT_FETCH_SUCCESS = 'FETCH_PRODUCT_FETCH_SUCCESS';
export const FETCH_PRODUCT_FETCH_FAILURE = 'FETCH_PRODUCT_FETCH_FAILURE';



